"""Semantic memory: durable facts stored relationally (SQL), queryable by entity/relation.

The `memory_id` that links facts to their episode is generated by the database,
not the LLM. :meth:`create_memory` returns that id after inserting the episode.
"""
from __future__ import annotations

import logging
import uuid
from dataclasses import asdict
from typing import Sequence

from sqlalchemy import select
from sqlalchemy.orm import Session, sessionmaker

from database.models import Fact, Memory

from .models import MemoryFact
from .validator import FactValidator

logger = logging.getLogger(__name__)


class SemanticMemoryStore:
    """Relational store for episodes and their facts."""

    def __init__(
        self,
        session_factory: sessionmaker[Session],
        validator: FactValidator | None = None,
    ) -> None:
        self.session_factory = session_factory
        self.validator = validator or FactValidator()

    def create_memory(self, user_id: str, summary: str) -> uuid.UUID:
        """Insert an episode and return the database-generated `memory_id`."""
        with self.session_factory() as session:
            memory = Memory(user_id=user_id, summary=summary)
            session.add(memory)
            session.commit()
            session.refresh(memory)
            return memory.id

    def save_fact(self, memory_id: uuid.UUID | str, fact: MemoryFact) -> Fact | None:
        """Validate and persist a single fact. Returns the row, or None if rejected."""
        if not self.validator.validate_fact(fact):
            logger.debug("Rejected fact %s %s", fact.entity, fact.relation)
            return None
        with self.session_factory() as session:
            row = Fact(
                memory_id=memory_id,
                entity=fact.entity,
                relation=fact.relation,
                value=fact.value,
                confidence=fact.confidence,
                source=fact.source or None,
            )
            session.add(row)
            session.commit()
            session.refresh(row)
            return row

    def save_facts(
        self, memory_id: uuid.UUID | str, facts: Sequence[MemoryFact]
    ) -> list[Fact]:
        """Validate and persist many facts, returning the accepted rows."""
        rows: list[Fact] = []
        for fact in self.validator.validate(list(facts)):
            with self.session_factory() as session:
                row = Fact(
                    memory_id=memory_id,
                    entity=fact.entity,
                    relation=fact.relation,
                    value=fact.value,
                    confidence=fact.confidence,
                    source=fact.source or None,
                )
                session.add(row)
                session.commit()
                session.refresh(row)
                rows.append(row)
        return rows

    def query_fact(
        self, entity: str | None = None, relation: str | None = None, limit: int = 50
    ) -> list[dict]:
        """Query facts by entity and/or relation, returning plain dicts."""
        stmt = select(Fact)
        if entity:
            stmt = stmt.where(Fact.entity == entity)
        if relation:
            stmt = stmt.where(Fact.relation == relation)
        stmt = stmt.order_by(Fact.confidence.desc()).limit(limit)
        with self.session_factory() as session:
            rows = session.scalars(stmt).all()
            return [asdict(r) for r in rows]

    def get_facts_by_memory(self, memory_id: uuid.UUID | str) -> list[dict]:
        """Return all facts produced by a given episode."""
        stmt = select(Fact).where(Fact.memory_id == memory_id)
        with self.session_factory() as session:
            rows = session.scalars(stmt).all()
            return [asdict(r) for r in rows]
