apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coral.fullname" . }}
  labels:
    {{- include "coral.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "coral.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "coral.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "coral.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - '/app/entrypoint.sh'
          env:
            - name: K8S_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TENANT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: METRICS_TRACE_ENABLED
              value: '{{ .Values.config.trace.enabled }}'
            - name: METRICS_TRACE_ENDPOINT
              value: '{{ .Values.config.trace.endpoint }}'
            - name: BIOMNI_HOST
              value: '0.0.0.0'
            - name: BIOMNI_PORT
              value: '{{ .Values.service.port }}'
            - name: BIOMNI_DATA_PATH
              value: '{{ .Values.config.dataPath }}'
            - name: BIOMNI_LLM_MODEL
              value: '{{ .Values.config.llmModel }}'
            - name: BIOMNI_ENABLE_REACT
              value: '{{ .Values.config.enableReact }}'
            - name: BIOMNI_DEFAULT_AGENT
              value: '{{ .Values.config.defaultAgent }}'
            - name: BIOMNI_A1_TIMEOUT
              value: '{{ .Values.config.a1Timeout }}'
            - name: BIOMNI_REACT_TIMEOUT
              value: '{{ .Values.config.reactTimeout }}'
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: anthropic-api-key
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: gemini-api-key
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: openai-api-key
            - name: LANGFUSE_HOST
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: langfuse-host
            - name: LANGFUSE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: langfuse-public-key
            - name: LANGFUSE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: langfuse-secret-key
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.service.metricsPort }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
